// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFB7Wne_4gsoRB2YEVo4-9rcBY9_otDFk',
    appId: '1:656109020820:web:c8eef41955379d8de8f681',
    messagingSenderId: '656109020820',
    projectId: 'tembea-a8335',
    authDomain: 'tembea-a8335.firebaseapp.com',
    storageBucket: 'tembea-a8335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqOQUJees5rMr7Vmnkj1mmWCxVOBhUT8E',
    appId: '1:656109020820:android:f4f83271e4cceb3ce8f681',
    messagingSenderId: '656109020820',
    projectId: 'tembea-a8335',
    storageBucket: 'tembea-a8335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2rauEPYg73APUWyNAgE5NURso9uBOl4',
    appId: '1:656109020820:ios:6d634aea59043cfbe8f681',
    messagingSenderId: '656109020820',
    projectId: 'tembea-a8335',
    storageBucket: 'tembea-a8335.appspot.com',
    iosBundleId: 'com.example.tembea',
  );
}
